name: demo2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  dio: ^3.0.9
  fluttertoast: ^2.1.1
  shared_preferences: ^0.5.6+3
  sqflite: ^1.3.0
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.0.0
  provider: ^4.0.4
  rxdart: ^0.23.1
  flutter_easyrefresh: ^2.1.0
  flutter_easyloading: ^1.1.3
  webview_flutter: ^0.3.19+9
  multi_image_picker: ^4.6.5+rc.1
  image_picker: ^0.6.3+4
  video_player: ^0.10.8+1
  camera: ^0.5.7+4
  path_provider: ^0.5.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/files/
    # - assets/images/2.0x/
    # - assets/images/3.0x/
  
  # .../Mx/image.png
  # .../Nx/image.png

  fonts:
    - family: webfont
      fonts:
        - asset: assets/fonts/webfont.ttf
